# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'DouYin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouYin
pod 'SnapKit'
pod 'Just'
pod 'Kingfisher'
pod 'MarqueeLabel'
pod 'NVActivityIndicatorView'
pod 'ChainableAnimations'
pod 'lottie-ios'
pod 'FaveButton'

end
